### ISSUE TITLE
Case insensitive replacement

### ISSUE THREAD

**Issue by kristijanhusak** [lambdalisue/reword.vim#5]
Hi,

is there a way to do case insensitive replacements?

For example, if i have this:

```
fooBar
FooBar
foobar
```

Doing `%Reword` with any of these will not replace all of them.

I would like to have an option to do `%Reword/foobar/bazbaz` and have it replace all of them.

**Comment by lambdalisue** [comment]
You don't need reword.vim. Use Vim's native substitution like

```
:%s/foobar/bazbaz/i
```

**Comment by kristijanhusak** [comment]
You didn't understood. I want to do this:

```
%Reword/foobar/bazbaz
```

and get this:

```
bazBaz
BazBaz
bazbaz
```

**Comment by lambdalisue** [comment]
I see. Got it.

**Comment by lambdalisue** [comment]
@kristijanhusak Please try #6

**Comment by kristijanhusak** [comment]
@lambdalisue it works when i do `%Reword/FooBar/BazBaz`, but it doesn't replace all when i do `%Reword/foobar/bazbaz`.

**Comment by lambdalisue** [comment]
> but it doesn't replace all when i do %Reword/foobar/bazbaz.

It's not possible while there is no way to build `foo-bar` or `FooBar` or whatever from `foobar` machinary.

**Comment by kristijanhusak** [comment]
Yeah that's true. #6 solves it as much as possible, so let's go with that. Thanks.
